server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userDB
    username: root
    password: manju
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

app:
  constants:
    secretkey: My123SecretKey67Is25Inowegn3592njsgQwertYQ8733TUBYndrrug123456789
    expirationTime: 10000000